[package]
name = "cargo-dot"
version = "0.1.0"
authors = [
    "Max New <maxsnew@gmail.com>",
    "Kevin K. <kbknapp@gmail.com>"
]

[[bin]]
name = "cargo-dot"
test = false
doc = true

[dependencies]
toml = "~0.1.22"
clap = "~1.2.5"

[features]
default = []
unstable = []
nightly = []
debug = []

